### ISSUE TITLE
Resource not currently part of this pool

### ISSUE THREAD

**Issue by willin** [coopernurse/node-pool#196]
here's my log

i have two questions:

1. cause: what caused this happen. previous version without promise works well (on Aliyun, but we moved to Azure).
2. figure it out:  i have no idea about how to fix it.

source code at:

https://github.com/AirDwing/node-dwing-mysql/blob/master/src/pool.js#L62

```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Resource not currently part of this pool
    at Pool.release (/home/airdwing/projects/AirX/node_modules/generic-pool/lib/Pool.js:422:35)
    at Query.client.query [as _callback] (/home/airdwing/projects/AirX/node_modules/@dwing/mysql/src/pool.js:62:19)
    at Query.Sequence.end (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at /home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:226:14
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Resource not currently part of this pool
    at Pool.release (/home/airdwing/projects/AirX/node_modules/generic-pool/lib/Pool.js:422:35)
    at Query.client.query [as _callback] (/home/airdwing/projects/AirX/node_modules/@dwing/mysql/src/pool.js:62:19)
    at Query.Sequence.end (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at /home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:226:14
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Resource not currently part of this pool
    at Pool.release (/home/airdwing/projects/AirX/node_modules/generic-pool/lib/Pool.js:422:35)
    at Query.client.query [as _callback] (/home/airdwing/projects/AirX/node_modules/@dwing/mysql/src/pool.js:62:19)
    at Query.Sequence.end (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at /home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:226:14
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by sandfox** [comment]
in the function at https://github.com/AirDwing/node-dwing-mysql/blob/master/src/pool.js#L57 you are calling `db[key].release` twice, once on line 59, and then again on line 62. You should only call release once for a resource.
Also, on line 62 you are calling db[key].release` without any parameters (which is what causes `Error: Resource not currently part of this pool`)

**Comment by willin** [comment]
@sandfox  azure mysql lost connection after 8 hours (forced).

how to config timeout to avoid this problem occur again? 


- idleTimeoutMillis
- softIdleTimeoutMillis
- evictionRunIntervalMillis

which one shoud i set?

mine now:

```
min: 0,
max: 10,
idleTimeoutMillis: 30000,
log: process.env.DEBUG !== undefined
```

**Comment by sandfox** [comment]
The easiest thing to do is probably going to be adding a `validator` function to the `factory` and setting `testOnBorrow` to `true`.

```
factory.validate = (connection) => {
  return new Promise((resolve, reject)=>{
    connection.ping((err)=>{
      if(err){
        return reject(err)
      }
      resolve()
    })
  })
  
}
```

It's not perfect but it should mean that your `acquire` code block doesn't have to deal with dead clients.
