### ISSUE TITLE
NPM installation faliure

### ISSUE THREAD

**Issue by aankur** [coopernurse/node-pool#281]
Hi, npm installation is failing with 
```
npm install generic-pool --loglevel verbose -f

npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/home/testuser/.nvm/versions/node/v12.16.3/bin/node',
npm verb cli   '/home/testuser/.nvm/versions/node/v12.16.3/bin/npm',
npm verb cli   'install',
npm verb cli   'generic-pool',
npm verb cli   '--loglevel',
npm verb cli   'verbose',
npm verb cli   '-f'
npm verb cli ]
npm info using npm@6.14.4
npm info using node@v12.16.3
npm WARN using --force I sure hope you know what you are doing.
npm verb npm-session 5d13167abb6063a1
npm http fetch GET 304 https://registry.npmjs.org/generic-pool 317ms (from cache)
npm timing stage:rollbackFailedOptional Completed in 0ms
npm timing stage:runTopLevelLifecycles Completed in 484ms
npm verb stack SyntaxError: Unexpected end of JSON input while parsing near '...prettier":"^1.7.4","t'
npm verb stack     at JSON.parse (<anonymous>)
npm verb stack     at parseJson (/home/testuser/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
npm verb stack     at /home/testuser/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50
npm verb stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm verb cwd /home/testuser/nodeprojects/test-node-pool
npm verb Linux 4.15.0-101-generic
npm verb argv "/home/testuser/.nvm/versions/node/v12.16.3/bin/node" "/home/testuser/.nvm/versions/node/v12.16.3/bin/npm" "install" "generic-pool" "--loglevel" "verbose" "-f"
npm verb node v12.16.3
npm verb npm  v6.14.4
npm ERR! Unexpected end of JSON input while parsing near '...prettier":"^1.7.4","t'
npm verb exit [ 1, true ]
npm timing npm Completed in 725ms
```

**Comment by aankur** [comment]
Hi,
but installation from github directly is working,
```
npm install coopernurse/node-pool --loglevel verbose -f
```

**Comment by aankur** [comment]
seems to have fixed itself, likely npm issue
