### ISSUE TITLE
Consistently occuring `ResourceRequest timed out` Error

### ISSUE THREAD

**Issue by blue-int** [coopernurse/node-pool#298]
I deployed node instances using generic-pool through k8s.
But after some time, which varies from 3 days to a few weeks, the generic pool of pods spit out TimeoutError when they receive any resource request.
Therefore, I have to restart the pods when the error occurs, which is very annoying.
Have anyone experienced this kind of error before? 
The stack message is as follows.

```
TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/home1/irteam/deploy/x-ray/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
    at Timeout.bound (/home1/irteam/deploy/x-ray/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

Thank you very much.

**Comment by mjw-git** [comment]
did you resolve it?

**Comment by firasdib** [comment]
I'm seeing the same issue, did you ever find a resolution?
