### ISSUE TITLE
TimeoutError: ResourceRequest timed out

### ISSUE THREAD

**Issue by zhangkai0203** [coopernurse/node-pool#299]
TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/home/demo2/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
    at Timeout.bound (/home/demo2/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

**Comment by blue-int** [comment]
This is same as what I'm experiencing in https://github.com/coopernurse/node-pool/issues/298

**Comment by Adrianvcp** [comment]
any solution ?

**Comment by firasdib** [comment]
I'm seeing the same issue, did you ever find a resolution?
